class LanguageService:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(LanguageService, cls).__new__(cls)
            cls._instance._initialize()
        return cls._instance

    def _initialize(self):
        self._current_language = "en"
        self._translations = self._create_translations()
        self._listeners = []

    def _create_translations(self):
        return {
            "en": {
                "gender_distribution": "Gender Distribution",
                "brand_distribution": "Brand Distribution",
                "statistics": "Statistics",
                "others": "Others",
                "no_data": "No data available",
                "select_perfumery_first": "Please select a perfumery first",
                "no_out_of_stock": "No out-of-stock items found",
                "export_csv_success": "Successfully exported to CSV",
                "export_doc_success": "Successfully exported to DOC",
                "export_error": "Error during export",
                "out_of_stock_items": "Out of Stock Items",
                "out_of_stock_report": "Out of Stock Report for",
                "perfumes": "Perfumes",
                "title": "Perfume Management System",
                "language": "Language:",
                "details": "Perfume Details",
                "name": "Name:",
                "brand": "Brand:",
                "price": "Price ($):",
                "description": "Description:",
                "volume": "Volume (ml):",
                "concentration": "Concentration:",
                "gender": "Gender:",
                "image": "Image:",
                "preview": "Preview:",
                "browse": "Browse...",
                "add": "Add",
                "update": "Update",
                "delete": "Delete",
                "clear": "Clear",
                "search": "Search:",
                "filter_brand": "Filter by Brand:",
                "all_brands": "All Brands",
                "sort_by": "Sort by:",
                "descending": "Descending",
                "sort": "Sort",
                "ready": "Ready",
                "add_success": "Perfume added successfully",
                "update_success": "Perfume updated successfully",
                "delete_success": "Perfume deleted successfully",
                "error": "Error",
                "fill_required": "Please fill in all required fields",
                "confirm_delete": "Confirm Deletion",
                "confirm_delete_msg": "Are you sure you want to delete this perfume?",
                "male": "Male",
                "female": "Female",
                "unisex": "Unisex",
                "edc": "Eau de Cologne",
                "edt": "Eau de Toilette",
                "edp": "Eau de Parfum",
                "parfum": "Parfum",
                "perfumeries": "Perfumeries",
                "perfumery_details": "Perfumery Details",
                "perfumery_name": "Name:",
                "address": "Address:",
                "city": "City:",
                "phone": "Phone:",
                "email": "Email:",
                "manager": "Manager:",
                "inventory": "Inventory",
                "inventory_details": "Inventory Details",
                "perfumery": "Perfumery:",
                "perfume": "Perfume:",
                "quantity": "Quantity:",
                "available": "Available:",
                "out_of_stock": "Out of Stock",
                "export_csv": "Export to CSV",
                "export_doc": "Export to DOC",
                "perfumeries_list": "Perfumeries List",
                "add_perfumery": "Add Perfumery",
                "update_perfumery": "Update Perfumery",
                "delete_perfumery": "Delete Perfumery",
                "add_inventory": "Add Inventory",
                "update_inventory": "Update Inventory",
                "delete_inventory": "Delete Inventory",
                "select_perfumery": "Select Perfumery",
                "select_perfume": "Select Perfume",
                "all_perfumeries": "All Perfumeries",
                "available_at": "Available at:",
                "quantity_availability": "Quantity & Status:",
                "no_inventory": "Not available in any perfumery",
                "inventory_summary": "Inventory Summary:",
                "available_only": "Available Only",
                "out_of_stock_only": "Out of Stock Only",
                "all_items": "All Items",
                "all_cities": "All Cities",
                "show": "Show:",
                "apply_filter": "Apply Filter",
                "no_perfumeries": "No perfumeries found",
                "no_inventory_items": "No inventory items found",
                "filter_city": "Filter by City:",
                "fill_required_perfumery": "Please fill in all required perfumery fields (Name, Address, City)",
                "fill_required_inventory": "Please select a perfumery and perfume",
                "inventory_already_exists": "This perfume is already in this perfumery's inventory",
                "confirm_delete_perfumery": "Confirm Perfumery Deletion",
                "confirm_delete_perfumery_msg": "Are you sure you want to delete this perfumery? This will also delete all of its inventory.",
                "confirm_delete_inventory": "Confirm Inventory Deletion",
                "confirm_delete_inventory_msg": "Are you sure you want to delete this inventory item?",
                "create_perfumery_success": "Perfumery added successfully",
                "update_perfumery_success": "Perfumery updated successfully",
                "delete_perfumery_success": "Perfumery deleted successfully",
                "create_inventory_success": "Inventory item added successfully",
                "update_inventory_success": "Inventory item updated successfully",
                "delete_inventory_success": "Inventory item deleted successfully"
            },
            "fr": {
                "select_perfumery_first": "Veuillez d'abord sélectionner une parfumerie",
                "no_out_of_stock": "Aucun article en rupture de stock trouvé",
                "export_csv_success": "Exporté avec succès au format CSV",
                "export_doc_success": "Exporté avec succès au format DOC",
                "export_error": "Erreur lors de l'exportation",
                "out_of_stock_items": "Articles en Rupture de Stock",
                "out_of_stock_report": "Rapport des Articles en Rupture de Stock pour",
                "perfumes": "Parfums",
                "title": "Système de Gestion des Parfums",
                "language": "Langue:",
                "details": "Détails du Parfum",
                "name": "Nom:",
                "brand": "Marque:",
                "price": "Prix (€):",
                "description": "Description:",
                "volume": "Volume (ml):",
                "concentration": "Concentration:",
                "gender": "Genre:",
                "image": "Image:",
                "preview": "Aperçu:",
                "browse": "Parcourir...",
                "add": "Ajouter",
                "update": "Mettre à jour",
                "delete": "Supprimer",
                "clear": "Effacer",
                "search": "Recherche:",
                "filter_brand": "Filtrer par Marque:",
                "all_brands": "Toutes les Marques",
                "sort_by": "Trier par:",
                "descending": "Décroissant",
                "sort": "Trier",
                "ready": "Prêt",
                "add_success": "Parfum ajouté avec succès",
                "update_success": "Parfum mis à jour avec succès",
                "delete_success": "Parfum supprimé avec succès",
                "error": "Erreur",
                "fill_required": "Veuillez remplir tous les champs obligatoires",
                "confirm_delete": "Confirmer la Suppression",
                "confirm_delete_msg": "Êtes-vous sûr de vouloir supprimer ce parfum?",
                "male": "Homme",
                "female": "Femme",
                "unisex": "Unisexe",
                "edc": "Eau de Cologne",
                "edt": "Eau de Toilette",
                "edp": "Eau de Parfum",
                "parfum": "Parfum",
                "perfumeries": "Parfumeries",
                "perfumery_details": "Détails de la Parfumerie",
                "perfumery_name": "Nom:",
                "address": "Adresse:",
                "city": "Ville:",
                "phone": "Téléphone:",
                "email": "Email:",
                "manager": "Gérant:",
                "inventory": "Inventaire",
                "inventory_details": "Détails de l'Inventaire",
                "perfumery": "Parfumerie:",
                "perfume": "Parfum:",
                "quantity": "Quantité:",
                "available": "Disponible:",
                "out_of_stock": "Rupture de Stock",
                "export_csv": "Exporter en CSV",
                "export_doc": "Exporter en DOC",
                "perfumeries_list": "Liste des Parfumeries",
                "add_perfumery": "Ajouter une Parfumerie",
                "update_perfumery": "Mettre à jour la Parfumerie",
                "delete_perfumery": "Supprimer la Parfumerie",
                "add_inventory": "Ajouter à l'Inventaire",
                "update_inventory": "Mettre à jour l'Inventaire",
                "delete_inventory": "Supprimer de l'Inventaire",
                "select_perfumery": "Sélectionner une Parfumerie",
                "select_perfume": "Sélectionner un Parfum",
                "all_perfumeries": "Toutes les Parfumeries",
                "available_at": "Disponible à:",
                "quantity_availability": "Quantité & Statut:",
                "no_inventory": "Non disponible dans aucune parfumerie",
                "gender_distribution": "Distribution par Genre",
                "brand_distribution": "Distribution par Marque",
                "statistics": "Statistiques",
                "others": "Autres",
                "no_data": "Aucune donnée disponible",
                "inventory_summary": "Résumé de l'Inventaire:",
                "available_only": "Disponibles Uniquement",
                "out_of_stock_only": "En Rupture de Stock Uniquement",
                "all_items": "Tous les Articles",
                "all_cities": "Toutes les Villes",
                "show": "Afficher:",
                "apply_filter": "Appliquer le Filtre",
                "no_perfumeries": "Aucune parfumerie trouvée",
                "no_inventory_items": "Aucun article d'inventaire trouvé",
                "filter_city": "Filtrer par Ville:",
                "fill_required_perfumery": "Veuillez remplir tous les champs obligatoires de la parfumerie (Nom, Adresse, Ville)",
                "fill_required_inventory": "Veuillez sélectionner une parfumerie et un parfum",
                "inventory_already_exists": "Ce parfum est déjà dans l'inventaire de cette parfumerie",
                "confirm_delete_perfumery": "Confirmer la Suppression de la Parfumerie",
                "confirm_delete_perfumery_msg": "Êtes-vous sûr de vouloir supprimer cette parfumerie? Cela supprimera également tout son inventaire.",
                "confirm_delete_inventory": "Confirmer la Suppression de l'Inventaire",
                "confirm_delete_inventory_msg": "Êtes-vous sûr de vouloir supprimer cet article d'inventaire?",
                "create_perfumery_success": "Parfumerie ajoutée avec succès",
                "update_perfumery_success": "Parfumerie mise à jour avec succès",
                "delete_perfumery_success": "Parfumerie supprimée avec succès",
                "create_inventory_success": "Article d'inventaire ajouté avec succès",
                "update_inventory_success": "Article d'inventaire mis à jour avec succès",
                "delete_inventory_success": "Article d'inventaire supprimé avec succès"
            },
            "es": {
                "select_perfumery_first": "Por favor, seleccione primero una perfumería",
                "no_out_of_stock": "No se encontraron artículos agotados",
                "export_csv_success": "Exportado exitosamente a CSV",
                "export_doc_success": "Exportado exitosamente a DOC",
                "export_error": "Error durante la exportación",
                "out_of_stock_items": "Artículos Agotados",
                "out_of_stock_report": "Informe de Artículos Agotados para",
                "perfumes": "Perfumes",
                "title": "Sistema de Gestión de Perfumes",
                "language": "Idioma:",
                "details": "Detalles del Perfume",
                "name": "Nombre:",
                "brand": "Marca:",
                "price": "Precio (€):",
                "description": "Descripción:",
                "volume": "Volumen (ml):",
                "concentration": "Concentración:",
                "gender": "Género:",
                "image": "Imagen:",
                "preview": "Vista previa:",
                "browse": "Examinar...",
                "add": "Añadir",
                "update": "Actualizar",
                "delete": "Eliminar",
                "clear": "Limpiar",
                "search": "Buscar:",
                "filter_brand": "Filtrar por Marca:",
                "all_brands": "Todas las Marcas",
                "sort_by": "Ordenar por:",
                "descending": "Descendente",
                "sort": "Ordenar",
                "ready": "Listo",
                "add_success": "Perfume añadido con éxito",
                "update_success": "Perfume actualizado con éxito",
                "delete_success": "Perfume eliminado con éxito",
                "error": "Error",
                "fill_required": "Por favor complete todos los campos requeridos",
                "confirm_delete": "Confirmar Eliminación",
                "confirm_delete_msg": "¿Está seguro de que desea eliminar este perfume?",
                "male": "Hombre",
                "female": "Mujer",
                "unisex": "Unisex",
                "edc": "Eau de Cologne",
                "edt": "Eau de Toilette",
                "edp": "Eau de Parfum",
                "parfum": "Parfum",
                "perfumeries": "Perfumerías",
                "perfumery_details": "Detalles de la Perfumería",
                "perfumery_name": "Nombre:",
                "address": "Dirección:",
                "city": "Ciudad:",
                "phone": "Teléfono:",
                "email": "Email:",
                "manager": "Gerente:",
                "inventory": "Inventario",
                "inventory_details": "Detalles del Inventario",
                "perfumery": "Perfumería:",
                "perfume": "Perfume:",
                "quantity": "Cantidad:",
                "available": "Disponible:",
                "out_of_stock": "Agotado",
                "export_csv": "Exportar a CSV",
                "export_doc": "Exportar a DOC",
                "perfumeries_list": "Lista de Perfumerías",
                "add_perfumery": "Añadir Perfumería",
                "update_perfumery": "Actualizar Perfumería",
                "delete_perfumery": "Eliminar Perfumería",
                "add_inventory": "Añadir al Inventario",
                "update_inventory": "Actualizar Inventario",
                "delete_inventory": "Eliminar del Inventario",
                "select_perfumery": "Seleccionar Perfumería",
                "select_perfume": "Seleccionar Perfume",
                "all_perfumeries": "Todas las Perfumerías",
                "available_at": "Disponible en:",
                "quantity_availability": "Cantidad & Estado:",
                "no_inventory": "No disponible en ninguna perfumería",
                "gender_distribution": "Distribución por Género",
                "brand_distribution": "Distribución por Marca",
                "statistics": "Estadísticas",
                "others": "Otros",
                "no_data": "No hay datos disponibles",
                "inventory_summary": "Resumen del Inventario:",
                "available_only": "Solo Disponibles",
                "out_of_stock_only": "Solo Agotados",
                "all_items": "Todos los Artículos",
                "all_cities": "Todas las Ciudades",
                "show": "Mostrar:",
                "apply_filter": "Aplicar Filtro",
                "no_perfumeries": "No se encontraron perfumerías",
                "no_inventory_items": "No se encontraron artículos de inventario",
                "filter_city": "Filtrar por Ciudad:",
                "fill_required_perfumery": "Por favor complete todos los campos requeridos de la perfumería (Nombre, Dirección, Ciudad)",
                "fill_required_inventory": "Por favor seleccione una perfumería y un perfume",
                "inventory_already_exists": "Este perfume ya está en el inventario de esta perfumería",
                "confirm_delete_perfumery": "Confirmar Eliminación de Perfumería",
                "confirm_delete_perfumery_msg": "¿Está seguro de que desea eliminar esta perfumería? Esto también eliminará todo su inventario.",
                "confirm_delete_inventory": "Confirmar Eliminación de Inventario",
                "confirm_delete_inventory_msg": "¿Está seguro de que desea eliminar este artículo de inventario?",
                "create_perfumery_success": "Perfumería añadida con éxito",
                "update_perfumery_success": "Perfumería actualizada con éxito",
                "delete_perfumery_success": "Perfumería eliminada con éxito",
                "create_inventory_success": "Artículo de inventario añadido con éxito",
                "update_inventory_success": "Artículo de inventario actualizado con éxito",
                "delete_inventory_success": "Artículo de inventario eliminado con éxito"
            }
        }

    def get_current_language(self):
        return self._current_language

    def set_language(self, language_code):
        if language_code in self._translations:
            self._current_language = language_code
            self._notify_listeners()
            return True
        return False

    def get_text(self, key, default=None):
        if key in self._translations[self._current_language]:
            return self._translations[self._current_language][key]
        return default or key

    def get_languages(self):
        return list(self._translations.keys())

    def get_language_names(self):
        language_names = {
            "en": "English",
            "fr": "French",
            "es": "Spanish"
        }
        return [language_names.get(code, code) for code in self.get_languages()]

    def add_listener(self, listener):
        if listener not in self._listeners:
            self._listeners.append(listener)

    def remove_listener(self, listener):
        if listener in self._listeners:
            self._listeners.remove(listener)

    def _notify_listeners(self):
        for listener in self._listeners:
            if hasattr(listener, 'on_language_changed'):
                listener.on_language_changed(self._current_language)
